server:
  address: 0.0.0.0
  port: 8080
app:
  url.api.gateway: http://192.168.1.100:8080
  url.web.gateway: http://192.168.1.100:5173
  security:
    auth:
      device:
        session:
          expiration.seconds: 300
          interval.seconds: 5
      token:
        access.expiration-minutes: 20160
        refresh.expiration.days: 30
