server:
  port: 8080
spring:
  datasource:
    url: ${PIXPLAZE_DB_URL}
    username: ${PIXPLAZE_DB_USERNAME}
    password: ${PIXPLAZE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: "pixplaze-web-api"
app:
  web.gateway.url: http://pixpleze.net
  security:
    auth:
      device:
        session:
          expiration.seconds: 300
          interval.seconds: 5
      token:
        access:
          expiration.minutes: 2400
          signing:
            key: ${JWT_ACCESS_SECRET_KEY}
        refresh:
          expiration.days: 30
          signing:
            key: ${JWT_REFRESH_SECRET_KEY}
    cors:
      allowed-origins:
        - "*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      allow-credentials: true
