CREATE TABLE minecraft_server_bid (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    host VARCHAR(128) NOT NULL UNIQUE,
    port INT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING', -- PENDING | APPROVED
    integration VARCHAR(16) NOT NULL DEFAULT 'NATIVE', -- NATIVE | PLUGIN
    voucher_code_id BIGINT REFERENCES voucher_code(id) ON DELETE CASCADE,
    profile_id BIGINT REFERENCES profile(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
