CREATE TABLE minecraft_server (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    host VARCHAR(128) NOT NULL UNIQUE,
    motd VARCHAR(256) NOT NULL,
    is_license BOOLEAN NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
)