CREATE TABLE voucher_codes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code CHAR(8) NOT NULL UNIQUE,
    description VARCHAR(256),
    type VARCHAR(8) NOT NULL DEFAULT 'INVITE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE,
    activations_limit INT NOT NULL DEFAULT 1,
    activations_remaining INT NOT NULL DEFAULT 1
);
