CREATE TABLE minecraft_server_port (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    minecraft_server_id BIGINT REFERENCES minecraft_server(id) ON DELETE CASCADE,
    java INT NOT NULL CHECK (java BETWEEN 0 AND 65536) DEFAULT 25565,
    map INT NOT NULL CHECK (map BETWEEN 0 AND 65536) DEFAULT 25565,
    api INT NOT NULL CHECK (api BETWEEN 0 AND 65536) DEFAULT 25565
)